# Generated by Django 4.2.4 on 2023-09-02 18:22

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=150)),
                ('notice_sender', models.CharField(max_length=50)),
                ('notice_description', tinymce.models.HTMLField()),
            ],
        ),
    ]
