# Generated by Django 4.2.4 on 2023-09-02 19:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notices', '0004_notices_notice_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='notices',
            name='notice_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
